import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { options } from '../service/options'
import { getServerSession } from 'next-auth'
import Navbar from '@/app/componentes/geral/navbar/Navbar'
import Navbarauth from '@/app/componentes/geral/navbar/Navbarauth'
import Footer from '@/app/componentes/geral/footer/footer'
import Provider from '@/app/componentes/geral/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(options)
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          { session? <Navbarauth/> : <Navbar/>}
          <div className='my-20'>{children}</div>
            
          <Footer/>
        </Provider>
      </body>
    </html>
  )
}
